### ISSUE TITLE
Stop services before upgrading (and start up again after)

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice-packaging#11]
Currently we do no stop services when upgrading RPMs (dpkg too?). If you upgrade from `3.7.1` to `3.7.2`, `systemd` is no longer able to stop the previously running service.

This is because we switched form a PID/forking based service to a notify based service.

**Comment by bernardnormier** [comment]
Unable to reproduce when updating/upgrading from Ice 3.7.1 to Ice 3.7.2 on EL7. Tried both glacier2 (glacier2router.service) and IceGrid (icegridregistry.service). The services are correctly restarted at the end of the update/upgrade.
