### ISSUE TITLE
Default architecture should depend on the platform

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice-packaging#23]
https://github.com/zeroc-ice/ice-packaging/blob/1c4d1eb93138fafbb9a21f4a08040044d67cc5e1/ice/pypi/setup.py#L59-L60

This result in m1 machines building `x86_64` by default, we can set this based on the value of `platform.machine()` or use the compiler default if it produces the desired result.

See also https://forums.zeroc.com/discussion/46809/python-import-error-on-macbook-m1

**Comment by externl** [comment]
Ruby has the same issue here:

https://github.com/zeroc-ice/ice-packaging/blob/d71649a367bb7618dad154ba44d856a21356c697/ice/gem/extconf.rb#L33

I think we should drop the `-arch` flag. That's what we did with the regular C++ builds in https://github.com/zeroc-ice/ice
