### ISSUE TITLE
Use stdout/stderr as the default service logger with systemd

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice-packaging#3]
Currently our systemd services log to the syslog because they use forking mode. Once https://github.com/zeroc-ice/ice/issues/75 is completed they should be updated to use stdout/stderr so they can be when started with notify mode `journalctl` can be used to filter by unit.

eg. `journalctl -u icegridnode.service`

**Comment by pepone** [comment]
Another option is to implement a new logger for `systemd` using `sd_journal_print` https://www.freedesktop.org/software/systemd/man/sd_journal_print.html

**Comment by pepone** [comment]
Fixed in in 0bdc0fa0920416963d3f366d6cb70bef6a621df0
