### ISSUE TITLE
Provide python 2 and 3 RPMs on platforms that support both

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice-packaging#6]
Amzn1 and Amzn2 provide RPM packages for both Python 2 and 3, like for Debian based platforms, it would be logical to provide RPMs for both as well. Right now, we only provide a package for Python 2. We do test Python 3 however but build IcePy from  source with PyPI (if we fix this, don't forget to fix https://github.com/zeroc-ice/dist-utils/blob/d1a536be34e8da1b2bfd6ac990dc80aeb42fd4d5/lib/components/ice.py#L120)

**Comment by pepone** [comment]
SLES has 2.7 and 3.6
AMZN1 has 2.7 3.4 3.5 and 3.6
AMZN2 has 2.7 and 3.7

Do we want to support all versions?

**Comment by bernardnormier** [comment]
I would do it only for amzn2.
