### ISSUE TITLE
Create packages which install the ice repository.

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice-packaging#9]
For example to install [EPEL](https://fedoraproject.org/wiki/EPEL) you do so by installing the EPEL rpm:

```
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
```

We should create a similar one for Ice -`zeroc-ice-release-3.7.noarch.rpm`

This is quite common for RPM based distros, is this also true for dpkg based repos?

**Comment by bernardnormier** [comment]
The zeroc-ice-repo RPMS are in https://zeroc.com/download/ice/3.7/el7/ and
https://zeroc.com/download/ice/3.7/amzn2/

**Comment by externl** [comment]
What about for dpkg?

**Comment by pepone** [comment]
We should update the instructions in the web page to use the RPMs 

https://zeroc.com/downloads/ice#redhat

Regarding DPKG  seems like using  `apt-add-repository` or downloading the `.list` file is the standard way to do that, I will not bother adding a package for debian/ubuntu.
